Repository FACG4/supply-change, pull requests merged in 2018-08, with the labels that each got.

#27 SE Profile
  client/src/Components/App.js
  client/src/Components/CommonComponents/Header/style.css
  client/src/Components/Pages/SEInformation/SocialImpact/.gitkeep
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/Place.png
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/Team.png
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/Vector.png
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/compUrl.png
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/facebook.png
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/instagram.png
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/mail.png
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/phoneCall.png
  client/src/Components/Pages/SEProfile/MainInfo/Imgs/twitter.png
  client/src/Components/Pages/SEProfile/MainInfo/index.js
  client/src/Components/Pages/SEProfile/MainInfo/style.css
  client/src/Components/Pages/SEProfile/PlacesToWork/.gitkeep
  client/src/Components/Pages/SEProfile/PlacesToWork/index.js
  client/src/Components/Pages/SEProfile/PlacesToWork/style.css
  client/src/Components/Pages/SEProfile/index.js
  client/src/Components/Pages/SEProfile/style.css
  client/src/Components/Pages/Signup/style.css
Labels: front-end, waiting-review

#25 Home components
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/CommonComponents/Footer/.gitkeep
  client/src/Components/CommonComponents/Footer/Style.css
  client/src/Components/CommonComponents/Footer/index.js
  client/src/Components/CommonComponents/Footer/logo.svg
  client/src/Components/Pages/HomePage/HeroSection/Style.css
  client/src/Components/Pages/HomePage/HeroSection/index.js
  client/src/Components/Pages/HomePage/HomeHeader/.gitkeep
  client/src/Components/Pages/HomePage/HomeHeader/Style.css
  client/src/Components/Pages/HomePage/HomeHeader/index.js
  client/src/Components/Pages/HomePage/HomeHeader/logo.svg
  client/src/Components/Pages/HomePage/HowItWork/.gitkeep
  client/src/Components/Pages/HomePage/HowItWork/Style.css
  client/src/Components/Pages/HomePage/HowItWork/index.js
  client/src/Components/Pages/HomePage/Testimoinals/.gitkeep
  client/src/Components/Pages/HomePage/Testimoinals/Style.css
  client/src/Components/Pages/HomePage/Testimoinals/index.js
  client/src/Components/Pages/HomePage/Testimoinals/test.svg
Labels: front-end

#31 Company API route
  .gitignore
  package-lock.json
  package.json
  server/controllers/get_company_info.js
  server/controllers/index.js
  server/index.js
Labels: waiting-review

#24 Footer
  client/public/index.html
  client/src/Components/CommonComponents/Footer/Style.css
  client/src/Components/Pages/HomePage/HeroSection/Style.css
  client/src/Components/Pages/HomePage/HeroSection/index.js
Labels: front-end, waiting-review

#39 React router
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/CommonComponents/Header/CompanyAction.js
  client/src/Components/CommonComponents/Header/Nav.js
  client/src/Components/CommonComponents/Header/action.js
  client/src/Components/CommonComponents/Header/index.js
  client/src/Components/Pages/HomePage/HomeHeader/index.js
  client/src/Components/Pages/HomePage/Testimoinals/index.js
  client/src/Components/Pages/HomePage/index.js
  client/src/Components/Pages/SEProfile/index.js
Labels: front-end, waiting-review

#36 Turnover
  client/package.json
  client/src/Components/App.js
  client/src/Components/CommonComponents/Footer/index.js
  client/src/Components/Pages/HomePage/Testimoinals/index.js
  client/src/Components/Pages/HomePage/index.js
  client/src/Components/Pages/SEInformation/Turnover/.gitkeep
  client/src/Components/Pages/SEInformation/Turnover/Style.css
  client/src/Components/Pages/SEInformation/Turnover/index.js
  client/src/Components/Pages/SEInformation/Turnover/size.svg
  package-lock.json
  package.json
Labels: front-end, waiting-review

#43 Progress tracker
  client/src/Components/Pages/SEInformation/ProgressTracker/.gitkeep
  client/src/Components/Pages/SEInformation/ProgressTracker/Progress.js
  client/src/Components/Pages/SEInformation/ProgressTracker/index.js
  client/src/Components/Pages/SEInformation/ProgressTracker/style.css
Labels: front-end, waiting-review

#51 Search page
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/CommonComponents/Select/index.js
  client/src/Components/Pages/ResultPage/Contract/index.js
  client/src/Components/Pages/ResultPage/Contract/style.css
  client/src/Components/Pages/ResultPage/Result.js
  client/src/Components/Pages/ResultPage/SearchForm/Form.js
  client/src/Components/Pages/ResultPage/SearchForm/add_options.js
  client/src/Components/Pages/ResultPage/SearchForm/index.js
  client/src/Components/Pages/ResultPage/filter_data.js
  client/src/Components/Pages/ResultPage/index.js
  client/src/Components/Pages/ResultPage/style.css
  package-lock.json
  package.json
  server/controllers/index.js
  server/controllers/search.js
  server/index.js
Labels: back-end, front-end, waiting-review
